export interface ThemeTokens {
  background: string
  surface: string
  surfaceSecondary: string
  card: string
  cardTextPrimary: string
  cardTextSecondary: string
  cardTextMuted: string
  sidebar: string
  sidebarHover: string
  sidebarActive: string
  sidebarText: string
  sidebarTitle: string
  header: string
  border: string
  divider: string
  primary: string
  primaryHover: string
  secondaryBtnBg: string
  secondaryBtnText: string
  danger: string
  success: string
  warning: string
  textPrimary: string
  textSecondary: string
  textMuted: string
  placeholder: string
  inputBackground: string
  inputText: string
  tableHeader: string
  tableHeaderText: string
  tableRow: string
  tableText: string
  tableHover: string
  dialogBg: string
  shadow: string
  radius: string
}

export const lightTokens: ThemeTokens = {
  background: '#F8FAFC',
  surface: '#FFFFFF',
  surfaceSecondary: '#F1F5F9',
  card: '#FFFFFF',
  cardTextPrimary: '#1E293B',
  cardTextSecondary: '#475569',
  cardTextMuted: '#64748B',
  sidebar: '#FFFFFF',
  sidebarHover: '#F1F5F9',
  sidebarActive: '#2F80ED',
  sidebarText: '#475569',
  sidebarTitle: '#1E293B',
  header: '#FFFFFF',
  border: '#E2E8F0',
  divider: '#F1F5F9',
  primary: '#2F80ED',
  primaryHover: '#1D6FD8',
  secondaryBtnBg: '#FFFFFF',
  secondaryBtnText: '#1E293B',
  danger: '#EF4444',
  success: '#34A853',
  warning: '#F57C00',
  textPrimary: '#1E293B',
  textSecondary: '#64748B',
  textMuted: '#94A3B8',
  placeholder: '#94A3B8',
  inputBackground: '#F8FAFC',
  inputText: '#1E293B',
  tableHeader: '#F8FAFC',
  tableHeaderText: '#475569',
  tableRow: '#FFFFFF',
  tableText: '#1E293B',
  tableHover: '#F1F5F9',
  dialogBg: '#FFFFFF',
  shadow: '0 8px 24px rgba(0,0,0,0.04)',
  radius: '24px',
}

export const darkTokens: ThemeTokens = {
  background: '#111827',
  surface: '#202634',
  surfaceSecondary: '#263247',
  card: '#202634',
  cardTextPrimary: '#F9FAFB',
  cardTextSecondary: '#CBD5E1',
  cardTextMuted: '#94A3B8',
  sidebar: '#111827',
  sidebarHover: '#1F2937',
  sidebarActive: '#2563EB',
  sidebarText: '#CBD5E1',
  sidebarTitle: '#F8FAFC',
  header: '#111827',
  border: '#334155',
  divider: 'rgba(255,255,255,0.08)',
  primary: '#2F80ED',
  primaryHover: '#1D6FD8',
  secondaryBtnBg: '#263247',
  secondaryBtnText: '#F9FAFB',
  danger: '#EF4444',
  success: '#34A853',
  warning: '#F57C00',
  textPrimary: '#F8FAFC',
  textSecondary: '#CBD5E1',
  textMuted: '#94A3B8',
  placeholder: '#94A3B8',
  inputBackground: '#2B3548',
  inputText: '#F9FAFB',
  tableHeader: '#263247',
  tableHeaderText: '#F8FAFC',
  tableRow: '#202634',
  tableText: '#F9FAFB',
  tableHover: '#374151',
  dialogBg: '#202634',
  shadow: '0 8px 24px rgba(0,0,0,0.25)',
  radius: '24px',
}
